development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: example
  database: mysql
  host: fupl_db_1

# fupl_db_1 is the name of the database service instance (docker ps -a)
